version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - pixelsdb:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    restart: always

# TODO: api unable to connect to DB
  api:
    build:
        context: .
        dockerfile: api.Dockerfile
        target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # https://github.com/prisma/prisma/issues/1385
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:?No postgres user proivded}:${POSTGRES_PASSWORD:?No db password provided}@db:5432/${POSTGRES_DB:?No db provided}?schema=public
    command: yarn start:debug
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db

volumes:
    pixelsdb:

