
name: 'dev - test & deploy'

on:
  push:
    branches: feat/test_server

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: "Install Deps"
        run: yarn install --frozen-lockfile

      - name: "Test"
        run: yarn server:test

