
name: '[dev]: build, deploy'

on:
  push:
    branches: feat/nest

defaults:
  run:
    shell: bash

env:
  DOCKER_REGISTRY: calebcarithers

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: |
          source .github/scripts/build.sh
          export BUILD_ID="$GITHUB_SHA"
          buildApi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          source .github/scripts/build.sh
          export BUILD_ID="$GITHUB_SHA"
          pushImage

      - name: Ping webhook
        run: |
          curl http::/167.172.252.56:3009/serve-project-jurisdiction-stand-peak-elegant?SHA1=$GITHUB_SHA&env=staging

